---
- name: install common pkgs...
  become: unarchive_deps_privilege_escalation
  become_user: root
  package: name={{item}} state=present
  with_items:
    - tar
    - unzip
    - gzip
    - bzip2

